### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by rhillis2004** [pkkid/python-plexapi#147]
Searching for items with extended characters has caused crashes. Is this library only capable of handling ascii, or should I be encoding my search strings in UTF-8 or some other encoding?

**Comment by Hellowlol** [comment]
Example please.

**Comment by rhillis2004** [comment]
The album title supplied to searchAlbums method of music section was u'An Introduction to\u2026 Elliott Smith'. This is what I got:

Traceback (most recent call last):
  File "./sync_playlists.py", line 78, in <module>
    main()
  File "./sync_playlists.py", line 50, in main
    albums = section.searchAlbums(title=album_name)
  File "/usr/local/lib/python2.7/dist-packages/plexapi/library.py", line 279, in searchAlbums
    return self.search(libtype='album', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/plexapi/library.py", line 202, in search
    query = '/library/sections/%s/all%s' % (self.key, utils.joinArgs(args))
  File "/usr/local/lib/python2.7/dist-packages/plexapi/utils.py", line 221, in joinArgs
    value = str(args[key])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 18: ordinal not in range(128)
