### ISSUE TITLE
401 Unauthorized issues

### ISSUE THREAD

**Issue by stevezau** [pkkid/python-plexapi#155]
Hi,

When logging into my server with my plex username I can make API calls to mark entries as watched/unwatched.

I also want to log in as a friend and mark entries watched/unwatched (converting from Kodi). But when using the friends account i keep getting a 401 Unauthroized? Any ideas where i can look? I'm using this lib but it's probably something to do with plex?

Also, i'm using plexapi from git version.

**Comment by stevezau** [comment]
```
(401) unauthorized; <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
```

plex logs

```
Jul 21, 2017 22:45:45.812 [0x7f55aa7ff700] DEBUG - Auth: We found auth token (xxxxxxxxxxxxxxxxxxxx), enabling token-based authentication.
Jul 21, 2017 22:45:45.813 [0x7f55aa7ff700] DEBUG - Auth: authenticated user XXXXXX as XXXXX
Jul 21, 2017 22:45:45.813 [0x7f55753ef700] DEBUG - Request: [XXX.XXX.XXX:53922 (WAN)] GET / (17 live) GZIP Signed-in Token (XXXXX)
Jul 21, 2017 22:45:45.813 [0x7f55753ef700] DEBUG - (Capabilities) Platform 'Darwin' not matched by plugin platform requirements
Jul 21, 2017 22:45:45.814 [0x7f55a9ffe700] DEBUG - Completed: [XXX.XXX.XXX:53922] 200 GET / (16 live) GZIP 1ms 1371 bytes (pipelined: 1)
Jul 21, 2017 22:45:45.831 [0x7f55a9ffe700] DEBUG - Auth: We found auth token (xxxxxxxxxxxxxxxxxxxx), enabling token-based authentication.
Jul 21, 2017 22:45:45.831 [0x7f55a9ffe700] DEBUG - Auth: authenticated user XXXX as XXXX
Jul 21, 2017 22:45:45.831 [0x7f559c3ff700] DEBUG - Request: [XX.XX.XX.XX:53921 (WAN)] GET / (16 live) TLS GZIP Signed-in Token (XXXX)
Jul 21, 2017 22:45:45.832 [0x7f559c3ff700] DEBUG - (Capabilities) Platform 'Darwin' not matched by plugin platform requirements
Jul 21, 2017 22:45:45.833 [0x7f55a9ffe700] DEBUG - Completed: [XX.XX.XX.XX:53921] 200 GET / (15 live) TLS GZIP 1ms 1371 bytes (pipelined: 1)
Jul 21, 2017 22:45:54.580 [0x7f55aa7ff700] DEBUG - Auth: We found auth token (xxxxxxxxxxxxxxxxxxxx), enabling token-based authentication.
Jul 21, 2017 22:45:54.581 [0x7f55aa7ff700] DEBUG - Auth: authenticated user XXXX as XXXX
Jul 21, 2017 22:45:54.581 [0x7f55aa7ff700] DEBUG - Request: [XX.XX.XX.XX:53921 (WAN)] GET /library (17 live) TLS GZIP Signed-in Token ()
Jul 21, 2017 22:45:54.582 [0x7f55aa7ff700] DEBUG - Completed: [XX.XX.XX.XX:53921] 401 GET /library (17 live) TLS GZIP 0ms 338 bytes (pipelined: 2)
```

**Comment by Hellowlol** [comment]
Can you post the code you used to di this?

**Comment by stevezau** [comment]
Yeah sure, it's here

https://github.com/stevezau/kodi_watched_2_plex/blob/master/kodi_watched_2_plex.py#L88

**Comment by Hellowlol** [comment]
Thanks. Whats the traceback you get in the script?

**Comment by stevezau** [comment]
```Traceback (most recent call last):
  File "/Users/stevenadams/workspace/personal/kodi_watched_2_plex/kodi_watched_2_plex.py", line 89, in <module>
    plex_episodes = plex.library.section('TV Shows').search(unwatched=True, libtype='episode')
  File "/Users/stevenadams/workspace/personal/kodi_watched_2_plex/venv/lib/python2.7/site-packages/plexapi/server.py", line 163, in library
    data = self.query(Library.key)
  File "/Users/stevenadams/workspace/personal/kodi_watched_2_plex/venv/lib/python2.7/site-packages/plexapi/server.py", line 317, in query
    raise BadRequest('(%s) %s; %s' % (response.status_code, codename, errtext))
BadRequest: (401) unauthorized; <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>```

**Comment by Hellowlol** [comment]
Im not sure this will work. Are you sure its the correct password? I think you need to login to your server using HIS access token. See https://github.com/pkkid/python-plexapi/pull/152/files#diff-7295db57b85fa93ef30adb91cb620fb1R389 for a example on how to do this

**Comment by stevezau** [comment]
Yes, it's the correct password. I tested this by trying with an incorrect password which gives a different error. 

The thing is, in the Plex Server looks it does not show any 401 or any errors for that matter. It shows the user has a valid token.

Do you mean using get_token??

**Comment by Hellowlol** [comment]
Yes, look at the PR it should work. It it does Ping me back and ill add a loginAs merhod to simply this use case

**Comment by stevezau** [comment]
I'll report back here after i test it.

**Comment by stevezau** [comment]
I'm a bit confused here. 

How should i be logging in? So far i've got the following (which does not work).

Once i get the token, how would i call the library?

```        account = MyPlexAccount(args.plex_username, args.plex_password).user(args.plex_username)
        plex = account.resource(args.plex_server_name).connect()
        token = account.get_token(plex.machineIdentifier)
```

**Comment by Hellowlol** [comment]
Just to be clear. Are you toggling what you has watched on your friends plex server or what he has watched on yours?

**Comment by Hellowlol** [comment]
See https://github.com/pkkid/python-plexapi/pull/152/commits/670ca1f573860e3abda1743d50698579e9fb3e96 for a example

**Comment by stevezau** [comment]
@Hellowlol i'm toggling what a friend has watched on mine. But i was hoping both ways would/should work?

I've tried with the loginAs method but i get


```
Traceback (most recent call last):
  File "/Users/stevenadams/workspace/personal/kodi_watched_2_plex/kodi_watched_2_plex.py", line 79, in <module>
    user = plex.loginAs(args.plex_username)
  File "/Users/stevenadams/workspace/personal/kodi_watched_2_plex/venv/lib/python2.7/site-packages/plexapi/server.py", line 396, in loginAs
    user = self.myPlexAccount().user(user)
  File "/Users/stevenadams/workspace/personal/kodi_watched_2_plex/venv/lib/python2.7/site-packages/plexapi/server.py", line 187, in myPlexAccount
    self._myPlexAccount = MyPlexAccount(token=self._token)
  File "/Users/stevenadams/workspace/personal/kodi_watched_2_plex/venv/lib/python2.7/site-packages/plexapi/myplex.py", line 78, in __init__
    data, initpath = self._signin(username, password, timeout)
  File "/Users/stevenadams/workspace/personal/kodi_watched_2_plex/venv/lib/python2.7/site-packages/plexapi/myplex.py", line 83, in _signin
    return self.query(self.key), self.key
  File "/Users/stevenadams/workspace/personal/kodi_watched_2_plex/venv/lib/python2.7/site-packages/plexapi/myplex.py", line 151, in query
    raise BadRequest('(%s) %s; %s' % (response.status_code, codename, errtext))
BadRequest: (422) unprocessable_entity; <?xml version="1.0" encoding="UTF-8"?> <errors>   <error>Invalid token</error> </errors> 
```

**Comment by stevezau** [comment]
Actually, I think it works if i login as me then switch to another user on the PMS.

What i was hoping it would allow is for the user to login with their plex user, choose my PMS then mark items as watched.

**Comment by Hellowlol** [comment]
The issue it that the accessToken we use for the plex server dont have access to sections etc.

**Comment by Hellowlol** [comment]
Can you try: https://github.com/pkkid/python-plexapi/tree/fix_sections ?

**Comment by stevezau** [comment]
That seems to of fixed it :)

**Comment by stevezau** [comment]
When will that be merged?

**Comment by Hellowlol** [comment]
Dunno
