### ISSUE TITLE
401 Unauthorized for Samsung TV and Chrome players

### ISSUE THREAD

**Issue by UnR34L** [pkkid/python-plexapi#161]
Plex Media Server Version : 1.7.6.4058
OS: FreeBSD 11.0-STABLE
Python: 2.7.13
pip 9.0.1

Samsung App version: 3.1.0 (3.8.0)

websocket-client and requests are installed.

I'm getting a 401 Unauthorized error when I use the following code, with the Samsung TV and Chrome players,

Tried both token and MyPlex auth, works with other players like Plex Media Player.
Server and Clients are on the same Network.

**Code Used**

```
#!/usr/local/bin/python2.7

from plexapi.server import PlexServer
baseurl = 'http://192.168.0.54:32400'
token = 'TOKEN'
plex = PlexServer(baseurl, token)

ozzy = plex.library.section('Trailers').get('Ozzy')
client = plex.client("TV UE40KU6000")
client.playMedia(ozzy)
```

**Traceback**

```Traceback (most recent call last):
  File "./test.py", line 9, in <module>
    client = plex.client("TV UE40KU6000")
  File "/usr/local/lib/python2.7/site-packages/plexapi/server.py", line 238, in client
    return PlexClient(baseurl=baseurl, server=self, data=elem)
  File "/usr/local/lib/python2.7/site-packages/plexapi/client.py", line 73, in __init__
    self.connect(timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/plexapi/client.py", line 87, in connect
    data = self.query(self.key, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/plexapi/client.py", line 153, in query
    raise BadRequest('(%s) %s; %s %s' % (response.status_code, codename, response.url, errtext))
plexapi.exceptions.BadRequest: (401) unauthorized; http://192.168.0.54:32400/resources <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>```

**Comment by pkkid** [comment]
@UnR34L Can you try this again? I'm wondering if PR #160 fixed this for you as well.

**Comment by UnR34L** [comment]
@pkkid Looks like it hasn't made a difference. Tried it with both the Samsung TV App and Chrome, same error.

**Comment by UnR34L** [comment]
@pkkid #160 only fixed Plex Media Player, I've just noticed something with that PR.

Before the Android client would play video but it would give a error, with #160 it wont play anymore.

#160 with an Android Client
```
Traceback (most recent call last):
  File "./test.py", line 9, in <module>
    client = plex.client("Xperia Z5")
  File "/usr/local/lib/python2.7/site-packages/plexapi/server.py", line 244, in client
    raise NotFound('Unknown client name: %s' % name)
plexapi.exceptions.NotFound: Unknown client name: Xperia Z5
```

**Comment by Hellowlol** [comment]
Pull the master branch from github

**Comment by UnR34L** [comment]
@Hellowlol I did, no change.

**Comment by Hellowlol** [comment]
Well post the correct traceback/log since the old one it not a pull from master.

**Comment by UnR34L** [comment]
```
Traceback (most recent call last):
  File "./test.py", line 9, in <module>
    client = plex.client("TV UE40KU6000")
  File "/usr/local/lib/python2.7/site-packages/plexapi/server.py", line 243, in client
    return PlexClient(baseurl=baseurl, server=self, data=elem)
  File "/usr/local/lib/python2.7/site-packages/plexapi/client.py", line 73, in __init__
    self.connect(timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/plexapi/client.py", line 87, in connect
    data = self.query(self.key, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/plexapi/client.py", line 153, in query
    raise BadRequest('(%s) %s; %s %s' % (response.status_code, codename, response.url, errtext))
plexapi.exceptions.BadRequest: (401) unauthorized; http://192.168.0.54:32400/resources <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
```

**Comment by Hellowlol** [comment]
WHOs server are you connecting to?

**Comment by UnR34L** [comment]
My own, on the same network.

**Comment by JonnyWong16** [comment]
The issue might be on the Plex side. Remove the TV from your devices in Plex then sign in to the TV again.

**Comment by UnR34L** [comment]
@JonnyWong16 Same error as before.

**Comment by Hellowlol** [comment]
Can you post the full script please.

**Comment by UnR34L** [comment]
```
#!/usr/local/bin/python2.7

from plexapi.server import PlexServer
baseurl = 'http://192.168.0.54:32400'
token = 'TOKEN'
plex = PlexServer(baseurl, token)

alien = plex.library.section('1.Movies').get('Alien')
client = plex.client("TV UE40KU6000")
client.playMedia(alien)
```

**Comment by JonnyWong16** [comment]
Even with a different token?

**Comment by UnR34L** [comment]
I considered that, I'm using the token you get from the URL when you view a XML file.
I tried the token that plexpy uses, didn't work.

**Comment by Hellowlol** [comment]
Can you post the output from http://server:port/clients?X-Plex-Token=Token ?

**Comment by Hellowlol** [comment]
Can you post the output from http://server:port/clients?

**Comment by UnR34L** [comment]
```
<MediaContainer size="4">
<Server name="Xperia Z5" host="192.168.0.119" address="192.168.0.119" port="32500" machineIdentifier="a9f04dc3600aea75-com-plexapp-android" version="6.0.1.523" protocol="plex" product="Plex for Android" deviceClass="mobile" protocolVersion="1" protocolCapabilities="timeline,playback,navigation,mirror,playqueues"/>
<Server name="DESKTOP-B88TLB1" host="192.168.0.5" address="192.168.0.5" port="32433" machineIdentifier="yto27dcvbhakdfymrr8ntgld" version="2.0.7.687-9a9cbad4" protocol="plex" product="Plex Media Player" deviceClass="pc" protocolVersion="1" protocolCapabilities="navigation,playback,timeline,mirror,playqueues"/>
<Server name="Plex Web (Chrome)" host="192.168.0.54" address="192.168.0.54" port="32400" machineIdentifier="v1whqtd3d1nt28pyhojvfc21" version="3.9.1" protocol="plex" product="Plex Web" deviceClass="pc" protocolVersion="1" protocolCapabilities="timeline,playback,navigation,mirror,playqueues"/>
<Server name="TV UE40KU6000" host="192.168.0.54" address="192.168.0.54" port="32400" machineIdentifier="fy3od71o6ss" version="3.1.0 (3.8.0)" protocol="plex" product="Plex for Samsung" deviceClass="pc" protocolVersion="1" protocolCapabilities="timeline,playback,navigation,mirror,playqueues"/>
</MediaContainer>
```

**Comment by Hellowlol** [comment]
and http://server:port/resources?X-Plex-Token=Token please

**Comment by Hellowlol** [comment]
I think the issue is that the token isnt passed to Plexclient. Ill see if cant fix this later.

**Comment by UnR34L** [comment]
```
<MediaContainer size="2">
<Player machineIdentifier="fy3od71o6ss" deviceClass="pc" platform="Samsung" platformVersion="2.4.0" product="Plex for Samsung" protocol="plex" protocolCapabilities="timeline,playback,navigation,mirror,playqueues" protocolVersion="1" title="TV UE40KU6000" version="3.1.0 (3.8.0)"/>
<Player machineIdentifier="v1whqtd3d1nt28pyhojvfc21" deviceClass="pc" platform="Chrome" platformVersion="59.0" product="Plex Web" protocol="plex" protocolCapabilities="timeline,playback,navigation,mirror,playqueues" protocolVersion="1" title="Plex Web (Chrome)" version="3.9.1"/>
</MediaContainer>
```

**Comment by Hellowlol** [comment]
Can you try https://github.com/pkkid/python-plexapi/pull/167 ?

**Comment by Hellowlol** [comment]
Well if it plays on your tv its fixed :P You just have to handle the timeout in your script your self.

**Comment by UnR34L** [comment]
Weird, it doesn't always give that error.

Restarted the app, now it works perfectly, only giving a error when the app is minimized.

I remember being able to play a video on the phone app when the samsung tv app was minimized and it would bring it to the foreground, doesn't anymore -.-

Anyway, thanks for all your help fixing this @Hellowlol I appreciate it!
