### ISSUE TITLE
Unable to install. "No such file or directory: 'README.rst'"

### ISSUE THREAD

**Issue by WyseNynja** [pkkid/python-plexapi#170]
```
$ virtualenv env
New python executable in env/bin/python2.7
Also creating executable in env/bin/python
Installing setuptools, pip, wheel...done.
$ . env/bin/activate
(env) $ pip install plexapi
Collecting plexapi
  Using cached PlexAPI-3.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/kn/jrf9s0891vd0lm4k9nv0r6m40000gn/T/pip-build-qi7BAm/plexapi/setup.py", line 16, in <module>
        readme = open('README.rst', 'r').read()
    IOError: [Errno 2] No such file or directory: 'README.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/kn/jrf9s0891vd0lm4k9nv0r6m40000gn/T/pip-build-qi7BAm/plexapi/
```

**Comment by pkkid** [comment]
Merged your pull request and its building now, should be on pypi in a few minutes.

**Comment by WyseNynja** [comment]
Thank you!

**Comment by pkkid** [comment]
Gah, it also needed an update in MANIFEST.in.

commit 8d720f893adf564672f4e9a83e768f0113c9ef42
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Sun Aug 13 21:09:33 2017 -0400
Fix another reference to readme.md

**Comment by pkkid** [comment]
This is working now.
