### ISSUE TITLE
While Loop Connection Issue

### ISSUE THREAD

**Issue by AverageManVsPi** [pkkid/python-plexapi#238]
I'm using the following code as part of a while loop, to display the number of films in my Plex server, then update every 5 minutes:

```
		films = plex.library.section('Films')
		numfilm = len(films.search())
		numfilmstring = "Films: " + str(numfilm)
```
This works the first time, but when it comes round again (in the while loop), I get the following error (this is the lower section of the error):
```
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 224, i                                     n _get_conn
    conn.close()
  File "/usr/lib/python2.7/httplib.py", line 830, in close
    self.sock.close()   # close it manually... there may be other refs
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 212                                     , in close
    return self.connection.shutdown()
OpenSSL.SSL.Error: []
```

Google isn't helping much, but from my searching I think this has something to do with connections renaming open in urllib3? I don't know how to manually 'close' them before my code loops again, IF that is the issue (?).

Can anyone help at all?

**Comment by Hellowlol** [comment]
Can you share the code and the full traceback?

**Comment by pkkid** [comment]
It looks like the session may be expiring or something.  You probably want to put the line to create the plex object inside the for loop.

```python
while True:
    plex = PlexServer()
    films = plex.library.section('Films')
    numfilm = len(films.search())
    numfilmstring = "Films: " + str(numfilm)
    time.sleep(A_LONG_TIME)
```

**Comment by AverageManVsPi** [comment]
So my full code currently looks like this (i'm still learning Python):

```
#!/usr/bin/python
#
#--------------------------------------
#  20x4 code from https://www.raspberrypi-spy.co.uk/2012/08/20x4-lcd-module-control-using-python/
#  Plex code from https://github.com/pkkid/python-plexapi
#--------------------------------------
#
# The wiring for the LCD is as follows:
# 1 : GND
# 2 : 5V
# 3 : Contrast (0-5V)*
# 4 : RS (Register Select)
# 5 : R/W (Read Write)       - GROUND THIS PIN
# 6 : Enable or Strobe
# 7 : Data Bit 0             - NOT USED
# 8 : Data Bit 1             - NOT USED
# 9 : Data Bit 2             - NOT USED
# 10: Data Bit 3             - NOT USED
# 11: Data Bit 4
# 12: Data Bit 5
# 13: Data Bit 6
# 14: Data Bit 7
# 15: LCD Backlight +5V**
# 16: LCD Backlight GND
 
# Imports

import RPi.GPIO as GPIO
import time
from plexapi.myplex import MyPlexAccount
import subprocess
import os

# Set up Plex account & server details

account = MyPlexAccount('EMAIL', 'PASSWORD') # Email address and password
plex = account.resource('SERVER').connect()  # Returns a Plex Server instance
 
# Define GPIO to LCD mapping

LCD_RS = 7
LCD_E  = 8
LCD_D4 = 25
LCD_D5 = 24
LCD_D6 = 23
LCD_D7 = 18
LED_ON = 15
 
# Define some device constants

LCD_WIDTH = 20    # Maximum characters per line
LCD_CHR = True
LCD_CMD = False
 
LCD_LINE_1 = 0x80 # LCD RAM address for the 1st line
LCD_LINE_2 = 0xC0 # LCD RAM address for the 2nd line
LCD_LINE_3 = 0x94 # LCD RAM address for the 3rd line
LCD_LINE_4 = 0xD4 # LCD RAM address for the 4th line
 
# Timing constants
E_PULSE = 0.0005
E_DELAY = 0.0005
 
def main():
  # Main program block
 
  GPIO.setmode(GPIO.BCM)       # Use BCM GPIO numbers
  GPIO.setup(LCD_E, GPIO.OUT)  # E
  GPIO.setup(LCD_RS, GPIO.OUT) # RS
  GPIO.setup(LCD_D4, GPIO.OUT) # DB4
  GPIO.setup(LCD_D5, GPIO.OUT) # DB5
  GPIO.setup(LCD_D6, GPIO.OUT) # DB6
  GPIO.setup(LCD_D7, GPIO.OUT) # DB7
  GPIO.setup(LED_ON, GPIO.OUT) # Backlight enable
 
  # Initialise display
  lcd_init()

  while True:
		
		print "Updating info..."
		
		timelastchecked = time.time()+180
		
		print "-- Obtaining TV library stats..."
		tv = plex.library.section('TV')
		numtv = len(tv.search())
		numtvstring = "TV Shows: " + str(numtv)
		print "-- TV library stats obtained..."
		
		print "-- Obtaining Film library stats..."
		films = plex.library.section('Films')
		numfilm = len(films.search())
		numfilmstring = "Films: " + str(numfilm)
		print "-- Film library stats obtained..."
		
		f=os.popen("date +%T")
		for i in f.readlines():
			timereading=""
			timereading += i
			timereading = "Last check: " + timereading
			break
			
		print "Displaying information..."
		lcd_string("**Plex Server Info**",LCD_LINE_1,1)
		lcd_string(numtvstring,LCD_LINE_2,1)
		lcd_string(numfilmstring,LCD_LINE_3,1)
		lcd_string(timereading,LCD_LINE_4,1)
		
		#Second page can be used if required
		#lcd_string("abc",LCD_LINE_1,3)
		#lcd_string("def",LCD_LINE_2,3)
		#lcd_string("ghi",LCD_LINE_3,2)
		#lcd_string("jkl",LCD_LINE_4,2)
		
		time.sleep(300)
	
 
def lcd_init():
  # Initialise display
  lcd_byte(0x33,LCD_CMD) # 110011 Initialise
  lcd_byte(0x32,LCD_CMD) # 110010 Initialise
  lcd_byte(0x06,LCD_CMD) # 000110 Cursor move direction
  lcd_byte(0x0C,LCD_CMD) # 001100 Display On,Cursor Off, Blink Off
  lcd_byte(0x28,LCD_CMD) # 101000 Data length, number of lines, font size
  lcd_byte(0x01,LCD_CMD) # 000001 Clear display
  time.sleep(E_DELAY)
 
def lcd_byte(bits, mode):
  # Send byte to data pins
  # bits = data
  # mode = True  for character
  #        False for command
 
  GPIO.output(LCD_RS, mode) # RS
 
  # High bits
  GPIO.output(LCD_D4, False)
  GPIO.output(LCD_D5, False)
  GPIO.output(LCD_D6, False)
  GPIO.output(LCD_D7, False)
  if bits&0x10==0x10:
    GPIO.output(LCD_D4, True)
  if bits&0x20==0x20:
    GPIO.output(LCD_D5, True)
  if bits&0x40==0x40:
    GPIO.output(LCD_D6, True)
  if bits&0x80==0x80:
    GPIO.output(LCD_D7, True)
 
  # Toggle 'Enable' pin
  lcd_toggle_enable()
 
  # Low bits
  GPIO.output(LCD_D4, False)
  GPIO.output(LCD_D5, False)
  GPIO.output(LCD_D6, False)
  GPIO.output(LCD_D7, False)
  if bits&0x01==0x01:
    GPIO.output(LCD_D4, True)
  if bits&0x02==0x02:
    GPIO.output(LCD_D5, True)
  if bits&0x04==0x04:
    GPIO.output(LCD_D6, True)
  if bits&0x08==0x08:
    GPIO.output(LCD_D7, True)
 
  # Toggle 'Enable' pin
  lcd_toggle_enable()
 
def lcd_toggle_enable():
  # Toggle enable
  time.sleep(E_DELAY)
  GPIO.output(LCD_E, True)
  time.sleep(E_PULSE)
  GPIO.output(LCD_E, False)
  time.sleep(E_DELAY)
 
def lcd_string(message,line,style):
  # Send string to display
  # style=1 Left justified
  # style=2 Centred
  # style=3 Right justified
 
  if style==1:
    message = message.ljust(LCD_WIDTH," ")
  elif style==2:
    message = message.center(LCD_WIDTH," ")
  elif style==3:
    message = message.rjust(LCD_WIDTH," ")
 
  lcd_byte(line, LCD_CMD)
 
  for i in range(LCD_WIDTH):
    lcd_byte(ord(message[i]),LCD_CHR)
 
def lcd_backlight(flag):
  # Toggle backlight on-off-on
  GPIO.output(LED_ON, flag)
 
if __name__ == '__main__':
 
  try:
    main()
  except KeyboardInterrupt:
    pass
  finally:
    lcd_byte(0x01, LCD_CMD)
    lcd_string("Goodbye!",LCD_LINE_1,2)
    GPIO.cleanup()
```

A lot of that is 20x4 LCD code that I'm pushing the data to. The full traceback looks like this (includes prints until it fails):

```
pi@VESA-Pi:~/plex $ sudo python 20by4.py
Updating info...
-- Obtaining TV library stats...
-- TV library stats obtained...
-- Obtaining Film library stats...
-- Film library stats obtained...
Displaying information...
Updating info...
-- Obtaining TV library stats...
Traceback (most recent call last):
  File "20by4.py", line 206, in <module>
    main()
  File "20by4.py", line 86, in main
    tv = plex.library.section('TV')
  File "/usr/local/lib/python2.7/dist-packages/plexapi/library.py", line 52, in                                      section
    for section in self.sections():
  File "/usr/local/lib/python2.7/dist-packages/plexapi/library.py", line 38, in                                      sections
    for elem in self._server.query(key):
  File "/usr/local/lib/python2.7/dist-packages/plexapi/server.py", line 340, in                                      query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 469, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in req                                     uest
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in sen                                     d
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in sen                                     d
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 511, i                                     n urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 224, i                                     n _get_conn
    conn.close()
  File "/usr/lib/python2.7/httplib.py", line 830, in close
    self.sock.close()   # close it manually... there may be other refs
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 212                                     , in close
    return self.connection.shutdown()
OpenSSL.SSL.Error: []
```

I tried adding `plex = PlexServer()` within the while loop, and then in other places, but I keep getting the same error (below). I'm using the 'MyPlexAccount' method - not sure if that makes a difference.
`NameError: name 'PlexServer' is not defined`

**Comment by Hellowlol** [comment]
https://repl.it/repls/BluevioletShockingBasenji i made some changes, try it and lets see how it goes.

**Comment by AverageManVsPi** [comment]
That works, I'm very grateful for your help. The script waited 5 minutes then updated everything.

Now I just need to work out how to use the rest of the API. I can't make much sense of anything that doesn't have an example :/
