### ISSUE TITLE
Timeout trying to use plexapi with Heroku app

### ISSUE THREAD

**Issue by RBWare** [pkkid/python-plexapi#239]
I wrote a really simple server based on the samples and just tried to get the server to start a single movie for me.

I have a method called `playMedia()`. When I receive ANY rest request, it's supposed to fire (so any POST/GET will trigger it).

That method looks like this...

```def playMedia():
    print("Signing into Plex Account...")
    from plexapi.server import PlexServer

    # baseurl = '<direct play URL>'
    # token = '<token>'
    # plex = PlexServer(baseurl, token)

    # plex_username = os.environ.get('PLEX_USERNAME')
    # plex_password = os.environ.get('PLEX_PASSWORD')
    # plex_server_name = os.environ.get('PLEX_SERVER_NAME')
    #
    plex_username = "<plex username>"
    plex_password = "<plex password>"
    plex_server_name = "<plex server name>"

    from plexapi.myplex import MyPlexAccount
    #
    plex_account = MyPlexAccount(plex_username, plex_password)
    plex = plex_account.resource(plex_server_name).connect()
    print(plex.accessToken)

    for client in plex.clients():
        print(client.title)

    print("Version")
    print(plex.version)

    # print(plex._baseurl)

    cars = plex.library.section("Movies").get("Cars")
    print("Found movie name")
    client = plex.client('Living Room')
    print("Setup client")
    client.playMedia(cars)
    print("Client should be playing.")
```

Obviously I removed a few of the things above for security reasons (anything inside of `<>` has actual data in it in my code).

Anyway... when I run my server on my dev machine, it works 100% of the time without issue. However, as soon as I drop the python server on my heroku instance, it fails.

Heroku Logs:
```2017-12-11T21:42:32.497839+00:00 heroku[web.1]: State changed from up to starting
2017-12-11T21:42:35.479919+00:00 heroku[web.1]: Starting process with command `python app.py`
2017-12-11T21:42:38.753826+00:00 app[web.1]: Starting app on port 55853
2017-12-11T21:42:38.817660+00:00 app[web.1]:  * Running on http://0.0.0.0:55853/ (Press CTRL+C to quit)
2017-12-11T21:42:39.209828+00:00 heroku[web.1]: State changed from starting to up
2017-12-11T21:42:56.570535+00:00 app[web.1]: Signing into Plex Account...
2017-12-11T21:43:28.283782+00:00 app[web.1]: Living Room
2017-12-11T21:43:28.283850+00:00 app[web.1]: Version
2017-12-11T21:43:28.283884+00:00 app[web.1]: 1.9.2.4285-9f65b88ae
2017-12-11T21:43:26.568665+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/webhook" host=some-random-app.herokuapp.com request_id=79ff6419-0028-4318-922d-9a17448ba336 fwd="35.202.88.64" dyno=web.1 connect=1ms service=30001ms status=503 bytes=0 protocol=https
2017-12-11T21:43:34.766682+00:00 app[web.1]: Found movie name
2017-12-11T21:43:34.944356+00:00 app[web.1]: Setup client
2017-12-11T21:44:05.904109+00:00 app[web.1]: Exception on /webhook [POST]
2017-12-11T21:44:05.904121+00:00 app[web.1]: Traceback (most recent call last):
2017-12-11T21:44:05.904125+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
2017-12-11T21:44:05.904126+00:00 app[web.1]:     (self.host, self.port), self.timeout, **extra_kw)
2017-12-11T21:44:05.904141+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
2017-12-11T21:44:05.904142+00:00 app[web.1]:     raise err
2017-12-11T21:44:05.904143+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
2017-12-11T21:44:05.904143+00:00 app[web.1]:     sock.connect(sa)
2017-12-11T21:44:05.904144+00:00 app[web.1]: socket.timeout: timed out
2017-12-11T21:44:05.904145+00:00 app[web.1]: 
2017-12-11T21:44:05.904146+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2017-12-11T21:44:05.904147+00:00 app[web.1]: 
2017-12-11T21:44:05.904148+00:00 app[web.1]: Traceback (most recent call last):
2017-12-11T21:44:05.904148+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
2017-12-11T21:44:05.904149+00:00 app[web.1]:     chunked=chunked)
2017-12-11T21:44:05.904150+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
2017-12-11T21:44:05.904150+00:00 app[web.1]:     conn.request(method, url, **httplib_request_kw)
2017-12-11T21:44:05.904152+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/http/client.py", line 1239, in request
2017-12-11T21:44:05.904152+00:00 app[web.1]:     self._send_request(method, url, body, headers, encode_chunked)
2017-12-11T21:44:05.904153+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/http/client.py", line 1285, in _send_request
2017-12-11T21:44:05.904153+00:00 app[web.1]:     self.endheaders(body, encode_chunked=encode_chunked)
2017-12-11T21:44:05.904154+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/http/client.py", line 1234, in endheaders
2017-12-11T21:44:05.904155+00:00 app[web.1]:     self._send_output(message_body, encode_chunked=encode_chunked)
2017-12-11T21:44:05.904156+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/http/client.py", line 1026, in _send_output
2017-12-11T21:44:05.904156+00:00 app[web.1]:     self.send(msg)
2017-12-11T21:44:05.904157+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/http/client.py", line 964, in send
2017-12-11T21:44:05.904157+00:00 app[web.1]:     self.connect()
2017-12-11T21:44:05.904158+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
2017-12-11T21:44:05.904158+00:00 app[web.1]:     conn = self._new_conn()
2017-12-11T21:44:05.904159+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/connection.py", line 146, in _new_conn
2017-12-11T21:44:05.904160+00:00 app[web.1]:     (self.host, self.timeout))
2017-12-11T21:44:05.904161+00:00 app[web.1]: urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f22ee46bba8>, 'Connection to <ipAddress> timed out. (connect timeout=30)')
2017-12-11T21:44:05.904162+00:00 app[web.1]: 
2017-12-11T21:44:05.904162+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2017-12-11T21:44:05.904163+00:00 app[web.1]: 
2017-12-11T21:44:05.904163+00:00 app[web.1]: Traceback (most recent call last):
2017-12-11T21:44:05.904164+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
2017-12-11T21:44:05.904165+00:00 app[web.1]:     timeout=timeout
2017-12-11T21:44:05.904165+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
2017-12-11T21:44:05.904166+00:00 app[web.1]:     _stacktrace=sys.exc_info()[2])
2017-12-11T21:44:05.904167+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
2017-12-11T21:44:05.904167+00:00 app[web.1]:     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2017-12-11T21:44:05.904176+00:00 app[web.1]: urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='<ipAddress>', port=32500): Max retries exceeded with url: /player/playback/playMedia?address=<directPlayAddress>&commandID=1&containerKey=/playQueues/1048%3Fwindow%3D100%26own%3D1&key=/library/metadata/2398&machineIdentifier=<machineIdentifier>&offset=0&port=32400&token=<plexToken>&X-Plex-Token=<plexToken> (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f22ee46bba8>, 'Connection to 192.168.2.208 timed out. (connect timeout=30)'))
2017-12-11T21:44:05.904177+00:00 app[web.1]: 
2017-12-11T21:44:05.904177+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2017-12-11T21:44:05.904178+00:00 app[web.1]: 
2017-12-11T21:44:05.904179+00:00 app[web.1]: Traceback (most recent call last):
2017-12-11T21:44:05.904179+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1817, in wsgi_app
2017-12-11T21:44:05.904180+00:00 app[web.1]:     response = self.full_dispatch_request()
2017-12-11T21:44:05.904181+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
2017-12-11T21:44:05.904182+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2017-12-11T21:44:05.904182+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1381, in handle_user_exception
2017-12-11T21:44:05.904183+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2017-12-11T21:44:05.904183+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
2017-12-11T21:44:05.904184+00:00 app[web.1]:     raise value
2017-12-11T21:44:05.904185+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
2017-12-11T21:44:05.904185+00:00 app[web.1]:     rv = self.dispatch_request()
2017-12-11T21:44:05.904186+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1461, in dispatch_request
2017-12-11T21:44:05.904186+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2017-12-11T21:44:05.904192+00:00 app[web.1]:   File "app.py", line 47, in webhook
2017-12-11T21:44:05.904193+00:00 app[web.1]:     res = processRequest(req)
2017-12-11T21:44:05.904193+00:00 app[web.1]:   File "app.py", line 60, in processRequest
2017-12-11T21:44:05.904194+00:00 app[web.1]:     playMedia()
2017-12-11T21:44:05.904194+00:00 app[web.1]:   File "/app/plex.py", line 37, in playMedia
2017-12-11T21:44:05.904195+00:00 app[web.1]:     client.playMedia(cars)
2017-12-11T21:44:05.904195+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/plexapi/client.py", line 462, in playMedia
2017-12-11T21:44:05.904196+00:00 app[web.1]:     }, **params))
2017-12-11T21:44:05.904197+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/plexapi/client.py", line 192, in sendCommand
2017-12-11T21:44:05.904197+00:00 app[web.1]:     return self.query(key, headers=headers)
2017-12-11T21:44:05.904201+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/plexapi/client.py", line 159, in query
2017-12-11T21:44:05.904202+00:00 app[web.1]:     response = method(url, headers=headers, timeout=timeout, **kwargs)
2017-12-11T21:44:05.904203+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
2017-12-11T21:44:05.904203+00:00 app[web.1]:     return self.request('GET', url, **kwargs)
2017-12-11T21:44:05.904204+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
2017-12-11T21:44:05.904205+00:00 app[web.1]:     resp = self.send(prep, **send_kwargs)
2017-12-11T21:44:05.904205+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
2017-12-11T21:44:05.904206+00:00 app[web.1]:     r = adapter.send(request, **kwargs)
2017-12-11T21:44:05.904207+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/requests/adapters.py", line 496, in send
2017-12-11T21:44:05.904207+00:00 app[web.1]:     raise ConnectTimeout(e, request=request)
2017-12-11T21:44:05.904208+00:00 app[web.1]: requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='<ipAddress>', port=32500): Max retries exceeded with url: /player/playback/playMedia?address=<directPlayAddress>&commandID=1&containerKey=/playQueues/1048%3Fwindow%3D100%26own%3D1&key=/library/metadata/2398&machineIdentifier=<machineIdentifier>&offset=0&port=32400&token=<plexToken>-Plex-Token=<plexToken> (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f22ee46bba8>, 'Connection to <ipAddress> timed out. (connect timeout=30)'))
2017-12-11T21:44:05.913639+00:00 app[web.1]: 10.165.157.61 - - [11/Dec/2017 21:44:05] "POST /webhook HTTP/1.1" 500 -
```

cURL command I'm using to test the Heroku app:
`curl -H "Content-Type: application/json" -X POST -d '{"username":"xyz","password":"xyz"}' https://some-random-app.herokuapp.com/webhook`

Device for Playback:
Apple TV on tvOS 11.2 (15k106)

Plex Server:
1.9.2.4285

**Comment by Hellowlol** [comment]
I think you need to be on the same lan. 
What try the playcommand manually from outside your network?

**Comment by RBWare** [comment]
It was only a test I was doing to make sure the connection/execution worked correctly. I don't plan on necessarily running `playMedia()` externally. But I would very much like to run a small Android app from my phone to run certain Plex-based APIs from outside my home network, if I'm not home.

**Comment by Hellowlol** [comment]
I don’t see any reasons why you shouldn’t be able to do this as long as the server is reachable from http.

**Comment by pkkid** [comment]
@RBWare are you still stuck on this, anything we can do from here to help you out?

**Comment by pkkid** [comment]
No response in 6 months; Closing.
