### ISSUE TITLE
my.plexapp.com certificate error with username/password

### ISSUE THREAD

**Issue by arsaboo** [pkkid/python-plexapi#246]
No errors, if we use a token. But, with username and password, it gives a certificate error. Here are the logs. 
```
>>> from plexapi.myplex import MyPlexAccount
>>> account = MyPlexAccount('<USERNAME>', '<PASSWORD>')
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\requests-2.10.0-py3.4.egg\requests\packages\urllib3\connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "C:\Python34\lib\site-packages\requests-2.10.0-py3.4.egg\requests\packages\urllib3\connectionpool.py", line 351, in _make_request
    self._validate_conn(conn)
  File "C:\Python34\lib\site-packages\requests-2.10.0-py3.4.egg\requests\packages\urllib3\connectionpool.py", line 814, in _validate_conn
    conn.connect()
  File "C:\Python34\lib\site-packages\requests-2.10.0-py3.4.egg\requests\packages\urllib3\connection.py", line 305, in connect
    _match_hostname(cert, self.assert_hostname or hostname)
  File "C:\Python34\lib\site-packages\requests-2.10.0-py3.4.egg\requests\packages\urllib3\connection.py", line 313, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "C:\Python34\lib\ssl.py", line 282, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname 'my.plexapp.com' doesn't match either of 'plex.tv', 'www.plex.tv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\requests-2.10.0-py3.4.egg\requests\adapters.py", line 403, in send
    timeout=timeout
  File "C:\Python34\lib\site-packages\requests-2.10.0-py3.4.egg\requests\packages\urllib3\connectionpool.py", line 604, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: hostname 'my.plexapp.com' doesn't match either of 'plex.tv', 'www.plex.tv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    account = MyPlexAccount('plexninjago', 'runway124')
  File "C:\Python34\lib\site-packages\plexapi\myplex.py", line 79, in __init__
    data, initpath = self._signin(username, password, timeout)
  File "C:\Python34\lib\site-packages\plexapi\myplex.py", line 87, in _signin
    data = self.query(self.SIGNIN, method=self._session.post, auth=(username, password), timeout=timeout)
  File "C:\Python34\lib\site-packages\plexapi\myplex.py", line 152, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "C:\Python34\lib\site-packages\requests-2.10.0-py3.4.egg\requests\sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python34\lib\site-packages\requests-2.10.0-py3.4.egg\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python34\lib\site-packages\requests-2.10.0-py3.4.egg\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python34\lib\site-packages\requests-2.10.0-py3.4.egg\requests\adapters.py", line 477, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname 'my.plexapp.com' doesn't match either of 'plex.tv', 'www.plex.tv'
```

**Comment by ryanm101** [comment]
PR with FIX
https://github.com/pkkid/python-plexapi/pull/247

**Comment by pkkid** [comment]
merged.
