### ISSUE TITLE
Error 404 "/library/metadata/"

### ISSUE THREAD

**Issue by reaperofpower** [pkkid/python-plexapi#309]
Any idea why I am getting the 404, I have the config setup with Key and URL not sure what I am missing.

python playlist_manager.py --jbop mostPopularMovies --action add --self --days 60 --top 10
Creating playlist(s)...
Traceback (most recent call last):
  File "playlist_manager.py", line 454, in <module>
    create_playlist(title, keys_list, x['server'], x['user'])
  File "playlist_manager.py", line 292, in create_playlist
    obj = plex.fetchItem(key)
  File "/usr/local/lib/python2.7/dist-packages/plexapi/base.py", line 136, in fetchItem
    for elem in self._server.query(ekey):
  File "/usr/local/lib/python2.7/dist-packages/plexapi/server.py", line 348, in query
    raise BadRequest('(%s) %s; %s %s' % (response.status_code, codename, response.url, errtext))
plexapi.exceptions.BadRequest: (404) not_found; http://localhost:32400/library/metadata/124822 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>

**Comment by pkkid** [comment]
Hey @reaperofpower, sorry I didn't get back to you yesterday. I assume because this is closed you got things working? Do you mind mentioning what the issue was to help others who may be in a similar situation in the future?

**Comment by reaperofpower** [comment]
The error listed below is caused when you have Metadata in the trash so it pulls this data when it no longer exists.

`(404) not_found; http://localhost:32400/library/metadata/124822 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>`

Fix:
Clean Bundles
Empty Trash
Optimize
