### ISSUE TITLE
ImportError: cannot import name 'log'

### ISSUE THREAD

**Issue by brettw1234** [pkkid/python-plexapi#375]
I'm attempting to use the most up-to-date version of the app (what is currently on master), and I'm getting this import error. I think it might be related to the changes for the most recent PR? I am not terribly familiar with how the Python import system works otherwise I would try to fix it!

```
Traceback (most recent call last):
  File "my_plex_script.py", line 1, in <module>
    from plexapi.server import PlexServer
  File "/home/brett/.local/lib/python3.6/site-packages/plexapi/__init__.py", line 7, in <module>
    from plexapi.utils import SecretsFilter
  File "/home/brett/.local/lib/python3.6/site-packages/plexapi/utils.py", line 12, in <module>
    from plexapi import compat, log
ImportError: cannot import name 'log'

```

**Comment by Hellowlol** [comment]
My bad. Should be ok now.
