### ISSUE TITLE
PlexServer.myPlexUsername returns server owner's email. Bug? Privacy issue?

### ISSUE THREAD

**Issue by e-Dan-K** [pkkid/python-plexapi#393]
The code:

```
	account = MyPlexAccount('USERNAME', 'PASSWORD')
	plex = account.resource('SERVERNAME').connect()
	connected_name = plex.myPlexUsername
```
ends up with `connected_name` as the email address of the server owner, when I would expect it to be the same as `'USERNAME'`. 
(Same issue if we log in via `plex = PlexServer(os.getenv('PLEX_BASEURL'), os.getenv('PLEX_TOKEN')`)

Shouldn’t `myPlexUsername` be the logged in username? Why not? And, if not a bug, how do I actually get the logged in username?

**Comment by Hellowlol** [comment]
It isn’t a bug. It’s what the info plex returns. I think it’s the username of account the server connected to. I don’t see any issues with privacy, they have shared this server with you...

**Comment by e-Dan-K** [comment]
OK. Is there any way to get the actual connected user's username then?

**Comment by amazingr4b** [comment]
Hellowlol is correct. If you go to your servers ip:port address and look at the xml response you'll see that that email is the server owners email. 

You'll likely need to give more details as to what you are trying to do. I'm guessing you are trying to do something like see who is playing what. If that is true I'd recommend looking at what you get from plex.sessions()

**Comment by e-Dan-K** [comment]
I'm actually trying to find the connection information of the current user, and not the server owner. My use case is that I've created a script that builds a webpage that gives you a sortable view into a better On Deck interface, based on the shows the user has watched and when they've watched them, or when they've aired, etc... (I had this as a plugin, but sadly that interface is no longer supported...)

As part of the page, I'm generating a link to the show page via the app.plex.tv URL (ie: `https://app.plex.tv/desktop#!/server/{machineIdentifier}/details?key=%2Flibrary%2Fmetadata%2{key}`)
This link works great, unless the user has a guest account set up on their account. In that case, I need to pass in a "username" to the URL, ie: `https://app.plex.tv/desktop#!/server/{machineIdentified}/details?key=%2Flibrary%2Fmetadata%2{key}&username={uname}`, to bypass the "select user" page.

To run the script, I've got just the PLEX_TOKEN and PLEX_BASEURL set in the environment, and I figured that based on that data, I should be able to get back to the username for that token.  Obviously I could just have them set their username in the environment, but I thought that would be redundant.

Is there some other API that would give me that token's user?

**Comment by blacktwin** [comment]
From the snippets you've provided, I'm thinking this is what you want.
`user_token = connected_name.get_token(plex.machineIdentifier)`

This is how I usually [access user's instance](https://github.com/pkkid/python-plexapi/issues/65#issuecomment-424405702) on my server:

```python
plex = PlexServer(PLEX_URL, PLEX_TOKEN)
account = plex.myPlexAccount()
user_acct = account.user('USERNAME')
user_plex = PlexServer(PLEX_URL, user_acct.get_token(plex.machineIdentifier))
```

**Comment by e-Dan-K** [comment]
Hmm, I run into a bad request if I attempt to use plex.myPlexAccount() on a server that I am not admin of. Running the code:
```
	account = MyPlexAccount(USERNAME, PASSWORD)
	plex = account.resource(SERVER).connect()
	acct = plex.myPlexAccount()
	Log(acct.username)
```
If SERVER is my server, I get the proper response. However if SERVER is a Friend's server that is shared with me (which is my target for the project), I get this error:
```
Traceback (most recent call last):
  File "tv.py", line 225, in <module>
    main()
  File "tv.py", line 213, in main
    testUsername()
  File "tv.py", line 32, in testUsername
    acct = plex.myPlexAccount()
  File "/usr/local/lib/python2.7/dist-packages/plexapi/server.py", line 205, in myPlexAccount
    self._myPlexAccount = MyPlexAccount(token=self._token)
  File "/usr/local/lib/python2.7/dist-packages/plexapi/myplex.py", line 83, in __init__
    data, initpath = self._signin(username, password, timeout)
  File "/usr/local/lib/python2.7/dist-packages/plexapi/myplex.py", line 88, in _signin
    return self.query(self.key), self.key
  File "/usr/local/lib/python2.7/dist-packages/plexapi/myplex.py", line 178, in query
    raise BadRequest('(%s) %s %s; %s' % (response.status_code, codename, response.url, errtext))
plexapi.exceptions.BadRequest: (422) unprocessable_entity https://plex.tv/users/account; <?xml version="1.0" encoding="UTF-8"?> <errors>   <error>Invalid token</error> </errors>

```

**Comment by blacktwin** [comment]
```python
user_account = MyPlexAccount('USERNAME', 'PASSWORD')
resource = user_account.resource("SERVER")
server = resource.connect()
```
`server` is now a user instance of the server they are connected to. `server.library.onDeck()` will return what's On Deck for user `USERNAME`, for instance. If you want the `USERNAME` you already have it, as it's needed to sign in, why are looking for it again? `user_account.username` will return the same name you used to sign in.

**Comment by e-Dan-K** [comment]
I'm actually connecting with:
```
	baseurl = os.getenv('PLEX_BASEURL')
	token = os.getenv('PLEX_TOKEN')
	plex = PlexServer(baseurl, token)
```
So I don't currently have the username saved. Again, I could easily set the Username as another environment variable. I just imagined that I should be able to find the Username from that `plex`, rather than needing to save it.

**Comment by blacktwin** [comment]
> I'm actually trying to find the connection information of the current user

Current user doing what? Currently watching something?
```python
#---your snippet---
for session in plex.sessions():
    print(session.usernames[0])
```
All users on your server can be accessed by using `plex.myPlexAccount().users()`.

```python
#---your snippet---
for user in plex.myPlexAccount().users():
    print(user.title, user.username)
````
`title` and `username` are different values. Typically, username is not assigned to Home users. 

```python
#---your snippet---
for session in plex.sessions():
    if username != plex.myPlexAccount().title:  # cannot use admin name
        plex_user = plex.myPlexAccount().user(username)
        user_token = plex_user.get_token(plex.machineIdentifier)
```
Now you have the username, user object, and user's token of the user that is currently watching something. 

No sure what else you're looking for as you haven't provided enough information to be useful. I've been guessing the entire time.

**Comment by e-Dan-K** [comment]
I'm not being obtuse. I'm literally only doing what I've said, not anything more. Concisely:

I have written a python script that generates a HTML page for the user specified by PLEX_TOKEN and PLEX_BASEURL. In that generated HTML page, one of the links needs the username of the user whose PLEX_TOKEN is specified. I am trying to find that username.

The user is not watching anything. The user is not the admin. Also, *I* am not the admin of the server. The user can be any user who has standard view access to that server. 

I'm just trying to get the username of the arbitrary user connected via PlexServer(PLEX_URL, PLEX_TOKEN)!

**Comment by pkkid** [comment]
I never log in as other users when using this library, so much of what people want to do in this area is new to us. I suspect it's the same problem. There are lots of way to get account details, and honestly I don't know the ins and outs of how they differ or why there is more than one way. But it's what the PlexWeb apis are calling, so we wired them in best we could.

Does `plex.account().username` give you the same result as `plex.myPlexAccount().username`?

**Comment by e-Dan-K** [comment]
> Do `plex.account().username` give you the same result as `plex.myPlexAccount().username`?

plex.account() gives a (401) unauthorized.
plex.myPlexAccount() gives a (422) unprocessable_entity, "Invalid Token" error.

> **EDIT:** When logging into my friends server and inspecting the XML returned from the server object, I do not actually see my username or email anywhere in the dataset. I am also getting forbidden errors when trying to access .account() and .myPlexAccount() on his plex_server object. It may not be available from the server instance, at least I am not seeing it. Perhaps a call is being made back to plex.tv to get the username? ¯\_(ツ)_/¯

Yeah, I'm beginning to think I just need to save the username as an additional login variable. Not the end of the world. I was just trying not to be redundant.

Thanks for checking, and thanks for the work on the API!

**Comment by blacktwin** [comment]
There are two token types, Server and Account. You cannot get the account token without the user's password and username or via OAuth. You, the server owner, can retrieve the user's server token to your server.

If you have the user's account `ACCOUNT_TOKEN` and are looking for their username then:
```python
user_account = MyPlexAccount(token=ACCOUNT_TOKEN)
print(user_account.title, user_account.username)
resource = user_account.resource(SERVERNAME)
connection = resource.connect()
print(connection) # Server object
```
With the user's Account Token you can traverse whatever servers they have access to.

**Comment by JonnyWong16** [comment]
There are two different tokens.

1. Account token - used to retrieve user info from Plex.tv, and
2. Server token - used to connect to a Plex server.

The account token can only be retrieved by using the username/password or via OAuth. The server token can be retrieved by using the account token and connecting to a server.

For server admins, the same token can be used for both account and server. But for user, the account token cannot be used to connect to a server, and the server token cannot be used to retrieve user info.
