### ISSUE TITLE
Traceback when accessing episode's show

### ISSUE THREAD

**Issue by jjlawren** [pkkid/python-plexapi#429]
I'm not certain of the conditions yet on when this occurs, but certain TV shows exhibit this behavior for me when accessing `grandparentKey`.

```
Traceback (most recent call last):
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/requests/models.py", line 379, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/urllib3/util/url.py", line 207, in parse_url
    raise LocationParseError(url)
urllib3.exceptions.LocationParseError: Failed to parse: 192-168-1-5.123456789012345678901234567890.plex.direct:32400None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/homeassistant/components/plex/sensor.py", line 113, in update
    if sess.show().year is not None:
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/plexapi/video.py", line 625, in show
    return self.fetchItem(self.grandparentKey)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/plexapi/base.py", line 137, in fetchItem
    for elem in self._server.query(ekey):
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/plexapi/server.py", line 376, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/requests/models.py", line 381, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: 192-168-1-5.123456789012345678901234567890.plex.direct:32400None
```

**Comment by Hellowlol** [comment]
depends on how the object was build. Check the xml, and try .reload

**Comment by blacktwin** [comment]
Might be because it's a [clip](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/plex/sensor.py#L112).

**Comment by jjlawren** [comment]
That's actually pointing to a newer change. [This]( https://github.com/home-assistant/home-assistant/blob/408b41ea020abfd70e8e11e0663c96ab35e183b5/homeassistant/components/plex/sensor.py#L112) is how it looked when the traceback occurred.

**Comment by blacktwin** [comment]
Is it a TV Show from a server owner's library or LiveTV or from one of Plex's new hubs?

> I'm not certain of the conditions yet

I'm not certain either. :) Also be sure to follow @Hellowlol 's [advice](https://github.com/pkkid/python-plexapi/issues/429#issuecomment-588513282).

**Comment by jjlawren** [comment]
It's media hosted on the Plex server. Still looking for a way to reproduce.

**Comment by jjlawren** [comment]
I grabbed the `/status/session` output when the error occurred, but I'm not certain it's representative.

```
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="1">
<Video addedAt="1431780991" art="/library/metadata/32456/art/1431781458" duration="1461408" grandparentArt="/library/metadata/32456/art/1431781458" grandparentGuid="com.plexapp.agents.thetvdb://76536?lang=en" grandparentRatingKey="32456" grandparentThumb="/library/metadata/32456/thumb/1431781458" grandparentTitle="Blue&#39;s Clues" guid="com.plexapp.agents.thetvdb://76536/5/13?lang=en" index="13" key="/library/metadata/32470" librarySectionID="4" originallyAvailableAt="2002-09-09" parentGuid="com.plexapp.agents.thetvdb://76536/5?lang=en" parentIndex="5" parentRatingKey="32457" parentThumb="/library/metadata/32457/thumb/1431781458" parentTitle="Season 5" ratingKey="32470" sessionKey="27" summary="In this episode, we have fun with the characters making boats and learning more about them. We learn how boats should be constructed and things that will cause them to sink or float. We help all of the characters to make sure that their boats float. Ia Blue Skidoo segment, we visit a beach filled with different types of boats. We help some of them to figure out why they&#39;re not moving, or going in circles. Then, we get to take an exciting ride on a speedboat." thumb="/library/metadata/32470/thumb/1454780409" title="The Boat Float" titleSort="Boat Float" type="episode" updatedAt="1454780409" viewOffset="1464826" year="2002">
<Media aspectRatio="1.33" audioChannels="2" audioCodec="mp3" bitrate="1763" container="avi" duration="1461408" height="512" id="37699" videoCodec="mpeg4" videoFrameRate="NTSC" videoProfile="advanced simple" videoResolution="480" width="656">
<Part container="avi" duration="1461408" file="/storage/kidtv/Blue&#39;s Clues/Season 05/Blue&#39;s Clues 05x13 The Boat Float.avi" id="37975" key="/library/parts/37975/1431780989/file.avi" size="324264708" videoProfile="advanced simple">
<Stream bitDepth="8" bitrate="1635" chromaLocation="left" chromaSubsampling="4:2:0" codec="mpeg4" displayTitle="480p (MPEG4)" frameRate="29.970" height="512" id="70635" index="0" level="1" profile="advanced simple" refFrames="1" streamType="1" width="656" />
<Stream audioChannelLayout="stereo" bitrate="128" channels="2" codec="mp3" displayTitle="Unknown (MP3 Stereo)" id="70636" index="1" samplingRate="48000" selected="1" streamIdentifier="1" streamType="2" />
</Part>
</Media>
<Director filter="director=22774" id="22774" tag="Alan Zdinak" />
<Writer filter="writer=22777" id="22777" tag="Jeff Borkin" />
<User id="user_id" thumb="https://plex.tv/users/1234/avatar?c=5678" title="user" />
<Player address="1.2.3.4" device="AFTT" machineIdentifier="machine_id" model="tank" platform="Android" platformVersion="5.1.1" product="Plex for Android (TV)" profile="Android" remotePublicAddress="1.2.3.4" state="paused" title="AFTT" vendor="Amazon" version="7.28.0.15501" local="0" relayed="0" secure="1" userID="user_id" />
<Session id="token=token" bandwidth="5077" location="wan" />
</Video>
</MediaContainer>
```

Looks like the `grandparentKey` and `parentKey` aren't in the `<Video>` element. It does have `grandparentRatingKey`/`parentRatingKey`/`ratingKey` and `key`, however.

Somehow the `grandparentKey` is still `None` when `Video.show()` is called which attempts to `fetchItem` with an empty key. This key passed through until it hits `Server.query(key)`, which then gets passed into `Server.url(key)` which returns a garbage URL when `None` is converted to a string.

**Comment by Hellowlol** [comment]
Hmm, i was sure we reload the object if we didnt have the info we needed. Anyway. A better fix is not to reload but in Episode().show()

```
def show(self):
    return self.fetchItem(int(self.grandparentRatingKey))
```
As this will result in one less api call to the server.

We should also check for None in the _build method.

**Comment by jjlawren** [comment]
Seems to be a similar potential issue in `Season().show()`, correct?

**Comment by Hellowlol** [comment]
Yes
