### ISSUE TITLE
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by pergolafabio** [pkkid/python-plexapi#439]
Hi

i have an older Samsung TV,  its not with the offical app from plex, but one from ORCA a volunteer

```
<MediaContainer size="1">
<Server name="TV Samsung" host="127.0.0.1" address="127.0.0.1" port="32400" machineIdentifier="mtcjs3w774g7i" version="2.012" protocol="plex" product="Plex for Samsung" deviceClass="tv" protocolVersion="1" protocolCapabilities="timeline,playback,navigation,mirror,playqueues"/>
</MediaContainer>

<MediaContainer size="1">
<Player machineIdentifier="mtcjs3w774g7i" deviceClass="tv" platform="Samsung" platformVersion="5.1" product="Plex for Samsung" protocol="plex" protocolCapabilities="timeline,playback,navigation,mirror,playqueues" protocolVersion="1" title="TV Samsung" version="2.012"/>
</MediaContainer>
```

what can be the issue?
sometimes it works, sometimes it doenst?

```
film = plex.library.section('Movies').get('Terminator Genisys')
client = plex.client("TV Samsung")
client.playMedia(film)
```
```


Traceback (most recent call last):
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\urllib3\connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\fabio.pergola\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\fabio.pergola\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\fabio.pergola\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\fabio.pergola\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\fabio.pergola\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 966, in send
    self.connect()
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\urllib3\connection.py", line 184, in connect
    conn = self._new_conn()
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001D32278CE08>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=32400): Max retries exceeded with url: /player/playback/playMedia?address=192.168.0.14&commandID=2&containerKey=/playQueues/3751%3Fwindow%3D100%26own%3D1&key=/library/metadata/3746&machineIdentifier=d0a25cbfa6fcc44d766dfea3abfc23b54c4caa5d&offset=0&port=32400&token=transient-2152cf74-84ea-48ff-bc65-f74033b6f161&type=video (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D32278CE08>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Documents/Downloads/Pyhton/project1/plex.py", line 11, in <module>
    client.playMedia(film)
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\client.py", line 496, in playMedia
    }, **params))
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\client.py", line 204, in sendCommand
    return query(key, headers=headers)
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\client.py", line 161, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=32400): Max retries exceeded with url: /player/playback/playMedia?address=192.168.0.14&commandID=2&containerKey=/playQueues/3751%3Fwindow%3D100%26own%3D1&key=/library/metadata/3746&machineIdentifier=d0a25cbfa6fcc44d766dfea3abfc23b54c4caa5d&offset=0&port=32400&token=transient-2152cf74-84ea-48ff-bc65-f74033b6f161&type=video (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D32278CE08>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

Process finished with exit code 1
```

**Comment by pergolafabio** [comment]
small update, i installed the "older" package on PMS : 

https://github.com/d8ahazard/Cast.bundle

that seems to work better, no connection error anymore

only this : 

```
Traceback (most recent call last):
  File "D:/Documents/Downloads/Pyhton/project1/plex.py", line 11, in <module>
    client.playMedia(film)
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\client.py", line 486, in playMedia
    }, **params))
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\client.py", line 204, in sendCommand
    return query(key, headers=headers)
  File "D:\Documents\Downloads\Pyhton\project1\venv\lib\site-packages\plexapi\client.py", line 168, in query
    return ElementTree.fromstring(data) if data.strip() else None
  File "C:\Users\fabio.pergola\AppData\Local\Programs\Python\Python37\lib\xml\etree\ElementTree.py", line 1316, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 54
```

**Comment by pergolafabio** [comment]
gonna close this one, my second error is not related

**Comment by blacktwin** [comment]
What is the output of your `client.protocolCapabilities`?

**Comment by pergolafabio** [comment]
Will let you know soon

**Comment by pergolafabio** [comment]
here it is : 

```
for client in plex.clients():
    print(client.title)
    print(client.protocolCapabilities)
```

=>

```
TV Samsung
['timeline', 'playback', 'navigation', 'mirror', 'playqueues']
```

**Comment by jjlawren** [comment]
Honestly it looks like the Samsung client is misbehaving and isn't listening for commands at all times.

**Comment by pergolafabio** [comment]
notthing we can do? or how can i help to troubleshoot?

**Comment by pergolafabio** [comment]
seems i also have the same error if i take "Chrome" as a client?

**Comment by jjlawren** [comment]
The client isn't reporting its real IP. You'll need to run `client.proxyThroughServer()` before sending it any commands.

**Comment by pergolafabio** [comment]
aha, that works
seems also now my samsung tv is working

**Comment by pergolafabio** [comment]
Gonna close this one , I think it's fixed with that extra command...
