### ISSUE TITLE
download related issues

### ISSUE THREAD

**Issue by MrDini123** [pkkid/python-plexapi#448]
Hi,

Since Plex doesn't have an option to directly mirror a complete server content, I am doing it via plexapi and a simple script. I do it as simple as follows:

```py
from pathlib import Path
from plexapi.myplex import MyPlexAccount

plex = MyPlexAccount('my_user', 'supersecret').resource('Da Server').connect()

movies = plex.library.section('Movies')
    print(movie.title)
    print(movie.download(savepath=Path.cwd()/f'{movie.title.replace(":", ".")}'))
```

However my first problem happened while pulling a 4K video over a not so powerfull server. On the webgui, upon opening I get a "server is not powerfull enough to play the content" error, but plexapi seems to simply download a 400 error in mkv format. Would be nice to check for those.

Then the next issue I have encountered is directly connected to how the download function was implemented:

https://github.com/pkkid/python-plexapi/blob/20160b9b4f327ed9cdddeb1f180033e976e793cc/plexapi/video.py#L263-L287

There is no check for actually valid file path names therefore the movie that has a : in its name, simply fails on Windows. I would recommend using sluggify to solve this problem.

Thanks

**Comment by Hellowlol** [comment]
Why not just keep the original file name?

**Comment by MrDini123** [comment]
It would be nice if we could specify a kwarg for the actual filename. I tried setting keep_original_name to both False and True, the : is always there. ? fails too.

The original file is on linux tho where these chars are probably allowed.

**Comment by MrDini123** [comment]
Also, sometimes my dl fails with:

```
Traceback (most recent call last):
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\response.py", line 639, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\response.py", line 397, in _error_catcher
    yield
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\response.py", line 704, in read_chunked
    self._update_chunk_length()
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\response.py", line 643, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\response.py", line 527, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\response.py", line 732, in read_chunked
    self._original_response.close()
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\response.py", line 415, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\main.py", line 20, in <module>
    print(movie.download())
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python37\lib\site-packages\plexapi\video.py", line 248, in download
    savepath=savepath, session=self._server._session)
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python37\lib\site-packages\plexapi\utils.py", line 286, in download
    for chunk in response.iter_content(chunk_size=chunksize):
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

If I restart the download, then it works. I wonder why. 🤔 Is that some ratelimit from Plex?
