### ISSUE TITLE
Plex server () error

### ISSUE THREAD

**Issue by BH1NBN** [pkkid/python-plexapi#497]
PlexAPI  3.6.0

Plexserver(‘http://127.0.0.1:32400’,‘<Token\>’)   = success
Plexserver(‘DDNS’,‘<Token\>’)   = success

\===================================
**Plexserver(‘http://app.plex.tv’,'<Token\>’)   =  error**
\===================================
```
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python37\lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Python37\lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\GitProjects\Easy-Plus\MediaInfoAPI\MediaInfoAPI-for-Serv\app\routs\plex\route.py", line 60, in plex_movie_update
    plex = PlexServer(BASEURL, token)#连接plex
  File "C:\Python37\lib\site-packages\plexapi\server.py", line 104, in __init__
    data = self.query(self.key, timeout=timeout)
  File "C:\Python37\lib\site-packages\plexapi\server.py", line 438, in query
    return ElementTree.fromstring(data) if data.strip() else None
  File "C:\Python37\lib\xml\etree\ElementTree.py", line 1315, in XML
    parser.feed(text)
File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 24, column 45
```

**Comment by Hellowlol** [comment]
You can’t use that url. If you don’t know the address use https://python-plexapi.readthedocs.io/en/latest/modules/myplex.html

**Comment by Wamy-Dev** [comment]
> You can’t use that url. If you don’t know the address use https://python-plexapi.readthedocs.io/en/latest/modules/myplex.html

why can't we use that url?
