### ISSUE TITLE
Travis failing tests

### ISSUE THREAD

**Issue by blacktwin** [pkkid/python-plexapi#499]
```
=================================== FAILURES ===================================
______________________ test_video_Show_attrs[anonymously] ______________________
Traceback (most recent call last):
  File "/home/travis/build/pkkid/python-[secure]/tests/test_video.py", line 352, in test_video_Show_attrs
    assert utils.is_int(show.duration, gte=1600000)
  File "/home/travis/build/pkkid/python-[secure]/tests/conftest.py", line 324, in is_int
    return int(value) >= gte
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

=================================== FAILURES ===================================
____________________ test_video_Movie_Media[authenticated] _____________________
Traceback (most recent call last):
  File "/home/travis/build/pkkid/python-[secure]/tests/test_video.py", line 352, in test_video_Movie_Media
    part.setDefaultAudioStream(ad[0])
IndexError: list index out of range

=================================== FAILURES ===================================
_____________________ test_audio_Album_attrs[anonymously] ______________________
Traceback (most recent call last):
  File "/home/travis/build/pkkid/python-plexapi/tests/test_audio.py", line 87, in test_audio_Album_attrs
    assert album.year in (2012,)
AssertionError: assert None in (2012,)
 +  where None = <Album:62:Layers>.year
_____________________ test_audio_Album_tracks[anonymously] _____________________
Traceback (most recent call last):
  File "/home/travis/build/pkkid/python-plexapi/tests/test_audio.py", line 116, in test_audio_Album_tracks
    assert utils.is_metadata(track.parentThumb, contains="/thumb/")
  File "/home/travis/build/pkkid/python-plexapi/tests/conftest.py", line 339, in is_metadata
    assert key.startswith(prefix)
AttributeError: 'NoneType' object has no attribute 'startswith'
_____________________ test_audio_Album_track[anonymously] ______________________
Traceback (most recent call last):
  File "/home/travis/build/pkkid/python-plexapi/tests/test_audio.py", line 146, in test_audio_Album_track
    assert track.originalTitle in (None, "As Colourful As Ever")
AssertionError: assert 'Broke For Free' in (None, 'As Colourful As Ever')
 +  where 'Broke For Free' = <Track:63:As-Colourful-as-Ever>.originalTitle
______________________ test_audio_Album_get[anonymously] _______________________
Traceback (most recent call last):
  File "/home/travis/build/pkkid/python-plexapi/tests/test_audio.py", line 196, in test_audio_Album_get
    test_audio_Album_track(album, track=track)
  File "/home/travis/build/pkkid/python-plexapi/tests/test_audio.py", line 146, in test_audio_Album_track
    assert track.originalTitle in (None, "As Colourful As Ever")
AssertionError: assert 'Broke For Free' in (None, 'As Colourful As Ever')
 +  where 'Broke For Free' = <Track:63:As-Colourful-as-Ever>.originalTitle
_____________________ test_audio_Track_attrs[anonymously] ______________________
Traceback (most recent call last):
  File "/home/travis/build/pkkid/python-plexapi/tests/test_audio.py", line 231, in test_audio_Track_attrs
    assert utils.is_metadata(track.parentThumb, contains="/thumb/")
  File "/home/travis/build/pkkid/python-plexapi/tests/conftest.py", line 339, in is_metadata
    assert key.startswith(prefix)
AttributeError: 'NoneType' object has no attribute 'startswith'
```

Looking at the failures it looks like the sample media items are causing an issue. Don't know if creating an issue like this is helpful or not.

**Comment by Hellowlol** [comment]
I have seen it, I dont have time to fix it now. The tests have passed before, i dont know if there is any changes to the metadata agents with the new pms version of its just flaky tests.

**Comment by palfrey** [comment]
Most of the rest seem fixed, but `test_audio_Album_attrs` seems flaky. Failed on https://travis-ci.org/github/pkkid/python-plexapi/jobs/725372000 and succeeded on https://travis-ci.org/github/pkkid/python-plexapi/jobs/725368005 with no relevant changes between.
