### ISSUE TITLE
Updating Collections Based On TV Studio

### ISSUE THREAD

**Issue by DutchyOven** [pkkid/python-plexapi#517]
I want to be able to add shows to a collection based on studio.

Below is the code and below that is the error I get at a certain point. I noticed timeouts so I'm wondering if my code isn't as efficient as it could be?

All I want to do is find any studio with the word Disney in it and add it to the Disney, disney has a ton of different studios so not all just say "disney" only. 

Also I'd like it to exclude anything already in Disney collection.

```
from plexapi.server import PlexServer
baseurl = 'http://192.168.1.2:32400'
token = 'dsfsdfdsfdsafdsafdsafdsa'
plex = PlexServer(baseurl, token)

show_section = plex.library.section('TV Shows')
added = show_section.search(sort='titleSort')

# Add all Disney Shows to Disney.

for show in added: 
    print('%s (%s)' % (show.title, show.studio)) 
    if show.studio is None:
        pass
    elif "Disney" in show.studio:
        show.addCollection('Disney')
```

```
Avatar: The Last Airbender (Nickelodeon) ([<Collection:Animated>, <Collection:Fantasy>])
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.1.62', port=32400): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tv_addcollections_disney.py", line 12, in <module>
    print('%s (%s) (%s)' % (show.title, show.studio, show.collections))
  File "/home/michael/.local/lib/python3.7/site-packages/plexapi/base.py", line 308, in __getattribute__
    self.reload()
  File "/home/michael/.local/lib/python3.7/site-packages/plexapi/base.py", line 212, in reload
    data = self._server.query(key)
  File "/home/michael/.local/lib/python3.7/site-packages/plexapi/server.py", line 432, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.1.62', port=32400): Read timed out. (read timeout=30)
```

**Comment by blacktwin** [comment]
Code works fine for me but as the error messages suggest, your connection to you server is timing out. 

Also you can't add an item more than once to a collection. So no issue with your script as is.

**Comment by DutchyOven** [comment]
Oh yeah I figured it wouldn't but just thinking of ways of limiting what it looks at. Can I just use timeout() and extend it? Its all wired but my server is pretty big and active so sometimes things take a minute to digest. If not maybe I'll limit out shows by rating? 

Also i like poking around in your JBOPS but is there anywhere else people post there out scripts? Would love some examples and just general stuff people do with plexapi.

**Comment by Hellowlol** [comment]
You can patch the session obects. See https://stackoverflow.com/questions/41295142/is-there-a-way-to-globally-override-requests-timeout-setting

https://github.com/pkkid/python-plexapi/network/dependents?package_id=UGFja2FnZS01MjQxNzk4MA%3D%3D

**Comment by blacktwin** [comment]
> Would love some examples and just general stuff people do with plexapi.

There is the [/tools directory](https://github.com/pkkid/python-plexapi/tree/master/tools) that has some useful scripts.

@DutchyOven If these suggestions have helped, can you please close this issue?

**Comment by DutchyOven** [comment]
@Hellowlol 

I'll poke around with that code, thanks!
