### ISSUE TITLE
TV show fails to load librarySectionID attribute

### ISSUE THREAD

**Issue by jjlawren** [pkkid/python-plexapi#550]
**Describe the issue**
One specific show fails to load the `librarySectionID` attribute. Other shows in the same library do not encounter this issue. The user has refreshed the metadata for both the series and the specific episode the the issue persists.

**Code snipppets**
```
from plexapi.server import PlexServer

baseurl = 'https://192-168-1-80.997198749174.plex.direct:32400'
token = '<YOUR_TOKEN_HERE>'

server = PlexServer(baseurl, token)
show = server.library.section('TV Shows').get('<SHOW_NAME_HERE>')
print(f"show: {show}")
season = show.season(1)
print(f"season: {season}")
episode = season.episode(episode=1)
print(f"episode: {episode}")
print(vars(episode))
print(f"Library Section: {episode.librarySectionID}")
```

Output from working examples:
```
show: <Show:10:The-Americans-(2013)>
season: <Season:93:The-Americans-(2013)-s1>
episode: <Episode:94:The-Americans-(2013)-s01e01>
{'_server': <PlexServer:https://p00.bluemagg>, '_data': <Element 'Video' at 0x7fd6b6bb35e0>, '_initpath': '/library/metadata/93/children', '_details_key': '/library/metadata/94?checkFiles=1&includeExtras=1&includeRelated=1&includeOnDeck=1&includeChapters=1&includePopularLeaves=1&includeMarkers=1&includeConcerts=1&includePreferences=1', 'listType': 'video', 'addedAt': datetime.datetime(2018, 8, 29, 17, 55, 56), 'key': '/library/metadata/94', 'lastViewedAt': datetime.datetime(2018, 8, 30, 23, 56, 22), 'librarySectionID': None, 'ratingKey': 94, 'summary': 'The Americans is a period drama about the complex marriage of two KGB spies posing as Americans in suburban Washington D.C. shortly after Ronald Reagan is elected President. The arranged marriage of Philip and Elizabeth Jennings grows more passionate and genuine by the day, but is constantly tested by the escalation of the Cold War. Tensions heighten upon the arrival of a new neighbor, Stan Beeman, an FBI agent. ', 'thumb': '/library/metadata/94/thumb/1579807227', 'title': 'Pilot', 'titleSort': 'Pilot', 'type': 'episode', 'updatedAt': datetime.datetime(2020, 1, 23, 13, 20, 27), 'viewCount': 1, 'sessionKey': None, 'usernames': [], 'players': [], 'transcodeSessions': [], 'session': [], 'viewedAt': None, 'accountID': None, 'playlistItemID': None, '_seasonNumber': '1', 'art': '/library/metadata/10/art/1579807227', 'chapterSource': None, 'contentRating': 'TV-MA', 'duration': 4265248, 'grandparentArt': '/library/metadata/10/art/1579807227', 'grandparentKey': '/library/metadata/10', 'grandparentRatingKey': 10, 'grandparentTheme': '/library/metadata/10/theme/1579807227', 'grandparentThumb': '/library/metadata/10/thumb/1579807227', 'grandparentTitle': 'The Americans (2013)', 'guid': 'com.plexapp.agents.thetvdb://261690/1/1?lang=en', 'index': 1, 'originallyAvailableAt': datetime.datetime(2013, 1, 30, 0, 0), 'parentIndex': '1', 'parentKey': '/library/metadata/93', 'parentRatingKey': 93, 'parentThumb': '/library/metadata/93/thumb/1579807227', 'parentTitle': 'Season 1', 'rating': 7.8, 'viewOffset': 0, 'year': 2013, 'directors': [], 'media': [<Media:145>], 'writers': [<Writer:Joe-Weisberg>], 'labels': [], 'collections': [], 'chapters': [], 'markers': []}
Library Section: 4
```

```
show: <Show:3566:Curb-Your-Enthusiasm>
season: <Season:3567:Curb-Your-Enthusiasm-s10>
episode: <Episode:3568:Curb-Your-Enthusiasm-s10e01>
{'_server': <PlexServer:https://p00.bluemagg>, '_data': <Element 'Video' at 0x7faaa20094f0>, '_initpath': '/library/metadata/3567/children', '_details_key': '/library/metadata/3568?checkFiles=1&includeExtras=1&includeRelated=1&includeOnDeck=1&includeChapters=1&includePopularLeaves=1&includeMarkers=1&includeConcerts=1&includePreferences=1', 'listType': 'video', 'addedAt': datetime.datetime(2020, 4, 15, 14, 7, 44), 'key': '/library/metadata/3568', 'lastViewedAt': None, 'librarySectionID': None, 'ratingKey': 3568, 'summary': 'Larry kicks off the new year with a new rival – Mocha Joe. Later, at a cocktail party hosted by Jeff and Susie, Larry gets roped into lunch plans and has a misunderstanding with a caterer.', 'thumb': '/library/metadata/3568/thumb/1586989710', 'title': 'Happy New Year', 'titleSort': 'Happy New Year', 'type': 'episode', 'updatedAt': datetime.datetime(2020, 4, 15, 17, 28, 30), 'viewCount': 0, 'sessionKey': None, 'usernames': [], 'players': [], 'transcodeSessions': [], 'session': [], 'viewedAt': None, 'accountID': None, 'playlistItemID': None, '_seasonNumber': '10', 'art': '/library/metadata/3566/art/1586989712', 'chapterSource': None, 'contentRating': 'TV-MA', 'duration': 2247804, 'grandparentArt': '/library/metadata/3566/art/1586989712', 'grandparentKey': '/library/metadata/3566', 'grandparentRatingKey': 3566, 'grandparentTheme': '/library/metadata/3566/theme/1586989712', 'grandparentThumb': '/library/metadata/3566/thumb/1586989712', 'grandparentTitle': 'Curb Your Enthusiasm', 'guid': 'com.plexapp.agents.thetvdb://76203/10/1?lang=en', 'index': 1, 'originallyAvailableAt': datetime.datetime(2020, 1, 19, 0, 0), 'parentIndex': '10', 'parentKey': '/library/metadata/3567', 'parentRatingKey': 3567, 'parentThumb': '/library/metadata/3567/thumb/1586989712', 'parentTitle': 'Season 10', 'rating': None, 'viewOffset': 0, 'year': 2020, 'directors': [], 'media': [<Media:4070>], 'writers': [], 'labels': [], 'collections': [], 'chapters': [], 'markers': []}
Library Section: 4
```
Failed lookup:
```
show: <Show:1497:Cowboy-Bebop>
season: <Season:1498:Cowboy-Bebop-s1>
episode: <Episode:1499:Cowboy-Bebop-s01e01>
{'_server': <PlexServer:https://*****>, '_data': <Element 'Video' at 0x7f9d44f814a0>, '_initpath': '/library/metadata/1498/children', '_details_key': '/library/metadata/1499?checkFiles=1&includeExtras=1&includeRelated=1&includeOnDeck=1&includeChapters=1&includePopularLeaves=1&includeMarkers=1&includeConcerts=1&includePreferences=1', 'listType': 'video', 'addedAt': datetime.datetime(2019, 7, 20, 21, 39, 15), 'key': '/library/metadata/1499', 'lastViewedAt': datetime.datetime(2019, 7, 20, 22, 48, 27), 'librarySectionID': None, 'ratingKey': 1499, 'summary': 'It\'s a normal day on the Bebop for bounty hunters Spike and Jet, until they find out about a new bounty hunter. Asimov Solensan is going around selling a new drug that he stole from the syndicate. It is an eyespray called "Bloody Eye" which makes all of its users very fast and almost invincible, but they also go crazy. Spike and Jet do whatever it takes to catch the culprit. At the same time the syndicate is trying to kill Asimov and get the drug back from him.\r\n', 'thumb': '/library/metadata/1499/thumb/1579807241', 'title': 'Asteroid Blues', 'titleSort': 'Asteroid Blues', 'type': 'episode', 'updatedAt': datetime.datetime(2020, 1, 23, 13, 20, 41), 'viewCount': 1, 'sessionKey': None, 'usernames': [], 'players': [], 'transcodeSessions': [], 'session': [], 'viewedAt': None, 'accountID': None, 'playlistItemID': None, '_seasonNumber': '1', 'art': '/library/metadata/1497/art/1579807242', 'chapterSource': 'media', 'contentRating': 'TV-MA', 'duration': 1482111, 'grandparentArt': '/library/metadata/1497/art/1579807242', 'grandparentKey': '/library/metadata/1497', 'grandparentRatingKey': 1497, 'grandparentTheme': '/library/metadata/1497/theme/1579807242', 'grandparentThumb': '/library/metadata/1497/thumb/1579807242', 'grandparentTitle': 'Cowboy Bebop', 'guid': 'com.plexapp.agents.thetvdb://76885/1/1?lang=en', 'index': 1, 'originallyAvailableAt': datetime.datetime(1998, 10, 24, 0, 0), 'parentIndex': '1', 'parentKey': '/library/metadata/1498', 'parentRatingKey': 1498, 'parentThumb': '/library/metadata/1498/thumb/1579807242', 'parentTitle': 'Season 1', 'rating': 7.9, 'viewOffset': 0, 'year': 1998, 'directors': [], 'media': [<Media:2143>], 'writers': [<Writer:Keiko-Nobumoto>], 'labels': [], 'collections': [], 'chapters': [], 'markers': []}
Traceback (most recent call last):
  File "./cb-dump", line 16, in <module>
    print(f"Library Section: {episode.librarySectionID}")
  File "/usr/local/lib/python3.8/site-packages/plexapi/base.py", line 308, in __getattribute__
    self.reload()
  File "/usr/local/lib/python3.8/site-packages/plexapi/base.py", line 213, in reload
    self._loadData(data[0])
  File "/usr/local/lib/python3.8/site-packages/plexapi/video.py", line 712, in _loadData
    self.markers = self.findItems(data, media.Marker)
  File "/usr/local/lib/python3.8/site-packages/plexapi/base.py", line 186, in findItems
    item = self._buildItemOrNone(elem, cls, initpath)
  File "/usr/local/lib/python3.8/site-packages/plexapi/base.py", line 88, in _buildItemOrNone
    return self._buildItem(elem, cls, initpath)
  File "/usr/local/lib/python3.8/site-packages/plexapi/base.py", line 73, in _buildItem
    return cls(self._server, elem, initpath)
  File "/usr/local/lib/python3.8/site-packages/plexapi/base.py", line 49, in __init__
    self._loadData(data)
  File "/usr/local/lib/python3.8/site-packages/plexapi/media.py", line 711, in _loadData
    _tag, _id = self.filter.split('=')
AttributeError: 'NoneType' object has no attribute 'split'
```

**Expected behavior**
Attribute should load successfully. This may be an issue on the Plex side and not the API, but a solution/workaround is still desired.

**Enviroment (please complete the following information):**
 - OS:
 - Plex version:
 - Python Version: 3.X (?)
 - PlexAPI version: 4.0.0

**Additional context**
Encountered by a user running Home Assistant which uses `plexapi`. Originally discussed [here](https://community.home-assistant.io/t/plex-play-media/202220/11).

**Comment by blacktwin** [comment]
What does Plex's XML show? What about reloading the episode? 

> The user has refreshed the metadata for both the series and the specific episode the the issue persists.

What about refreshing or scanning the library? What does the WebUI show for that episode? Does it play?

**Comment by jjlawren** [comment]
Yeah, they refreshed the metadata manually on both the show and the specific episode and the issue persisted. I'll ask the user to head over here to help troubleshoot.

**Comment by lidocaineus** [comment]
I'm attaching the XML for the first episode of the first season of the problematic show. It (and the rest of the season) plays fine on multiple clients on different platforms. Refreshing the metadata and rescanning the library has the same result.

Note that the actual XML returned by "Get Info / View XML" appears to have an actual librarySectionID attribute on the MediaContainer element.

[s01e01_xml.txt](https://github.com/pkkid/python-plexapi/files/5059174/s01e01_xml.txt)

**Comment by jjlawren** [comment]
I'm curious if it shows up in other responses. Like when you're actively playing the episode and request the current session XML?:
```
curl http://<PLEX_SERVER_IP>:32400/status/sessions?X-Plex-Token=<TOKEN>
```

**Comment by Hellowlol** [comment]
Accessing the librarysectionid triggere a reload. The problem is that the marker class dont have a filter attribute and it ends up with exception. Is this 4.0.0?

**Comment by jjlawren** [comment]
Yes, it's 4.0.0.

**Comment by lidocaineus** [comment]
Looks like while playing back in the web client the active session does return a librarySectionID attribute in the Video element (see attached, let me know if you prefer the outputs inline instead).

[s01e01_active-session.xml.txt](https://github.com/pkkid/python-plexapi/files/5059567/s01e01_active-session.xml.txt)

**Comment by Hellowlol** [comment]
Enable debug logging and check the url manually for the librarySectionID before the reload query. I suspect the attribute is missing from the xml respond that triggers a reload. The reload fail to build the marker class as the marker class xml object does not have a filter attribute. This default the filter to None and it blows up with a attribute error regarding split.

Btw, I think is is already fixed in the master branch

**Comment by blacktwin** [comment]
I was able to confirm the error then resolve it by updating plexapi using the following: 
`pip install --upgrade git+git://github.com/pkkid/python-plexapi.git`

Ran through my entire shows library without an issue where on previous version (forgot to record the version) I observed the report error.
```python
for show in plex.library.section('TV Shows').all():
    print(f"show: {show}")
    season = show.seasons()[0]
    print(f"season: {season}")
    episode = season.episodes()[0]
    print(f"episode: {episode}")
    print(vars(episode))
    print(f"Library Section: {episode.librarySectionID}")
```

Looks like @Hellowlol is correct in that this is fixed in master. Can you please confirm?

**Comment by jjlawren** [comment]
The next version of Home Assistant (0.115) will use 4.1.0 which will hopefully resolve this.

**Comment by jjlawren** [comment]
@lidocaineus please comment if you've run into this issue since upgrading and we can reopen.
