### ISSUE TITLE
Can't modify collections

### ISSUE THREAD

**Issue by zb140** [pkkid/python-plexapi#661]
**Describe the issue**
I'm trying to add and remove collections for various items in my library, but it always fails.  The issue seems to be that it doesn't have a `librarySectionID` for the items, so when I call `removeCollection` (for instance), the request URL doesn't get formed properly.  Maybe related to #550 ?

**Code snipppets**
```python
from plexapi.server import PlexServer

baseurl = '<plex url>'
token = '<plex token>'

server = PlexServer(baseurl, token)
item = server.library.section('Movies').get('Hawaiian Vacation')
print(vars(item))
print(vars(item.collections[0]))
print(f"Library Section: {item.librarySectionID}")
item.removeCollection(['Pixar Shorts'])
```

Output:
```
{'_server': <PlexServer:[...]:32400>, '_data': <Element 'Video' at 0x7ff72caf6c78>, '_initpath': '/library/sections/1/all?title=Hawaiian%20Vacation', '_parent': None, '_details_key': '/library/metadata/41384?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1', 'addedAt': datetime.datetime(2017, 11, 5, 9, 25, 8), 'art': '/library/metadata/41384/art/1610188896', 'artBlurHash': None, 'fields': [], 'guid': 'com.plexapp.agents.themoviedb://77887?lang=en', 'key': '/library/metadata/41384', 'lastViewedAt': None, 'librarySectionID': None, 'librarySectionKey': None, 'librarySectionTitle': None, 'listType': 'video', 'ratingKey': 41384, 'summary': "The toys throw Ken and Barbie a Hawaiian vacation in Bonnie's room.", 'thumb': '/library/metadata/41384/thumb/1610188896', 'thumbBlurHash': None, 'title': 'Hawaiian Vacation', 'titleSort': 'Hawaiian Vacation', 'type': 'movie', 'updatedAt': datetime.datetime(2021, 1, 9, 2, 41, 36), 'viewCount': 0, 'sessionKey': None, 'usernames': [], 'players': [], 'transcodeSessions': [], 'session': [], 'viewedAt': None, 'accountID': None, 'playlistItemID': None, 'playQueueItemID': None, 'audienceRating': None, 'audienceRatingImage': None, 'chapters': [], 'chapterSource': 'media', 'collections': [<Collection:Pixar-Shorts>], 'contentRating': 'G', 'countries': [<Country:USA>], 'directors': [<Director:Gary-Rydstrom>], 'duration': 353729, 'genres': [<Genre:Animation>, <Genre:Family>], 'guids': [], 'labels': [], 'media': [<Media:154811>], 'originallyAvailableAt': datetime.datetime(2011, 6, 24, 0, 0), 'originalTitle': None, 'primaryExtraKey': None, 'producers': [], 'rating': 6.9, 'ratingImage': None, 'roles': [<Role:Tom-Hanks>, <Role:Tim-Allen>, <Role:Joan-Cusack>], 'similar': [], 'studio': 'Pixar', 'tagline': None, 'userRating': None, 'viewOffset': 0, 'writers': [<Writer:Gary-Rydstrom>, <Writer:Jason-Katz>], 'year': 2011}
{'_server': <PlexServer:[...]:32400>, '_data': <Element 'Collection' at 0x7ff72cb131d8>, '_initpath': '/library/sections/1/all?title=Hawaiian%20Vacation', '_parent': <weakref at 0x7ff72caf69a8; to 'Movie' at 0x7ff72cb0b390>, '_details_key': None, 'id': None, 'role': None, 'tag': 'Pixar Shorts', 'key': None, 'librarySectionID': None, 'librarySectionTitle': None, 'librarySectionType': None, 'tagType': None, 'thumb': None}
Library Section: None
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "app/test.py", line 11, in <module>
    item.removeCollection(['Pixar Shorts'])
  File "[...]/.local/lib/python3.6/site-packages/plexapi/mixins.py", line 139, in removeCollection
    self._edit_tags('collection', collections, remove=True)
  File "[...]/.local/lib/python3.6/site-packages/plexapi/base.py", line 469, in _edit_tags
    self.edit(**d)
  File "[...]/.local/lib/python3.6/site-packages/plexapi/base.py", line 453, in edit
    self._server.query(part, method=self._server._session.put)
  File "[...]/.local/lib/python3.6/site-packages/plexapi/server.py", line 506, in query
    raise BadRequest(message)
plexapi.exceptions.BadRequest: (500) internal_server_error; [...]:32400/library/sections/None/all?collection%5B%5D.tag.tag-=Pixar+Shorts&collection.locked=1&id=41384&type=1 <html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body></html>
```
**Expected behavior**
The item should get removed from the collection.

**Enviroment (please complete the following information):**
 - OS: Linux
 - Plex version: 1.21.3.4015
 - Python Version: 3.6.9
 - PlexAPI version: I've tried both 4.3.1 and git master branch

**Additional context**
Add any other context about the issue here.

**Comment by zb140** [comment]
Ok, I don't understand why this had any effect, right after I submitted this ticket, I started having trouble connecting to my Plex server. It kept telling me my token was invalid.  I logged into my account, changed my password (and signed out of all devices), then got myself a new token.  Now my above example works perfectly.  Like I said, it makes no sense to me, but it doesn't seem to be an issue anymore...
